name = "DellReplicate"
uuid = "deb59c8e-8c3e-48d3-8e55-294d0bb3e50a"
authors = ["prantoine <pol.antoine@sciencespo.fr> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
